workflows:
  android-workflow:
    name: Build MyTunes APK
    max_build_duration: 30
    environment:
      android: true
    scripts:
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
